# Generated by Django 5.1.6 on 2025-02-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_doc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(default="General", max_length=50),
        ),
        migrations.AddField(
            model_name="blog",
            name="summary",
            field=models.TextField(default="ad"),
            preserve_default=False,
        ),
    ]
