# Generated by Django 5.1.6 on 2025-02-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blog_category_blog_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
